const Homeproduct =
[
    {
        id: 1,
        productname: 'p1',
        price:'100',
        url: '../../public/images/image2.jpeg',
        cat: 'laptop',
        description:'',
        stock:100,
    },
    {
        id: 2,
        productname: 'p2',
        price:'100',
        url: '../../public/images/image2.jpeg',
        cat: 'laptop',
        description:'',
        stock:100,
    },{
        id: 3,
        productname: 'p3',
        price:'100',
        url: '../../public/images/image2.jpeg',
        cat: 'desktop',
        description:'',
        stock:100,
    },{
        id: 4,
        productname: 'p4',
        price:'100',
        url: '../../public/images/image2.jpeg',
        cat: 'desktop',
        description:'',
        stock:100,
    },{
        id: 5,
        productname: 'p5',
        price:'100',
        url: '../../public/images/image2.jpeg',
        cat: 'desktop',
        description:'',
        stock:100,
    },{
        id: 6,
        productname: 'p6',
        price:'100',
        url: '../../public/images/image2.jpeg',
        cat: 'desktop',
        description:'',
        stock:100,
    },{
        id: 7,
        productname: 'p7',
        price:'100',
        url: '../../public/images/image2.jpeg',
        cat: 'desktop',
        description:'',
        stock:10,
    },{
        id: 8,
        productname: 'p8',
        price:'100',
        url: '../../public/images/image2.jpeg',
        cat: 'accessory',
        description:'',
        stock:10,
    },{
        id: 9,
        productname: 'p9',
        price:'100',
        url: '../../public/images/image2.jpeg',
        cat: 'accessory',
        description:'',
        stock:10,
    },{
        id: 10,
        productname: 'p10',
        price:'100',
        url: '../../public/images/image2.jpeg',
        cat: 'accessory',
        description:'',
        stock:10,
    }
]

export default Homeproduct